- name: Configure users
  user:
    name: "{{ item }}"
    groups: adm,staff,sudo
    shell: /bin/bash
    append: yes
  with_items:
    - piajesse
    - ave

- name: Configure SSH keys
  authorized_key:
    user: "{{ item.local }}"
    state: present
    key: "https://github.com/{{ item.github }}.keys"
  with_items:
    - github: piajesse
      local: piajesse
    - github: thesage1014
      local: ave

- name: Ensure passwordless sudo
  lineinfile:
    line: "%sudo	ALL=(ALL:ALL) NOPASSWD:ALL"
    dest: /etc/sudoers
    regexp: "^%sudo	ALL=\\(ALL:ALL\\).*"
